plugins { id 'com.android.application' }

android {
    namespace 'com.sooqflow.marketplace'
    compileSdk 35

    defaultConfig {
        applicationId 'com.sooqflow.marketplace'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {}
